[build]
    publish = "public/"
    command = "npm run build"

[[plugins]]
    package = "@netlify/plugin-gatsby"


## Temporary
[[redirects]]
  from = "/*"
  to = "https://realty100plus.com/"
  force = true